### ISSUE TITLE
Missing name & type in Nargo.toml

### ISSUE THREAD

**Issue by mozrt2** [sambarnes/noir-by-example#3]
Hi there, 

I just tried to get started with noir-by-example but was getting the following error when using `nargo test --show-output`: `Error: Missing 'name' field in /noir-by-example/circuits/examples/hello-world/Nargo.toml`

I believe this is related to the latest version of Noir (I am using 0.9.0) requiring a `name` and `type` in the Nargo.toml files. When adding the below to the Nargo.toml in the hello-world example, the test passes without error:
```
name = "hello world"
type = "bin"
```

I am planning to go through all examples over the coming days and could then make a PR with this adjustment for all examples. Just wanted to already highlight it here in case anyone else encounters the same problem.

**Comment by sambarnes** [comment]
@mozrt2 yoo :v: thanks for the heads up on this! i've been away from noir for a sec so didnt see this til now

i've updated all the basic examples with the requirements in latest nightly nargo

but looks like [some tests for the two gadgets pages ](https://github.com/sambarnes/noir-by-example/actions/runs/6126979417/job/16632001699) are failing on latest version -- if you wanted to take a stab at those still? otherwise i'll probs get to it eventually

**Comment by sambarnes** [comment]
see https://github.com/sambarnes/noir-by-example/issues/4

**Comment by mozrt2** [comment]
Hi @sambarnes - great, thanks for fixing these! I'm currently swamped with other stuff so not sure I'll be able to look into this issue - will let you know if I do end up finding some time!

**Comment by sambarnes** [comment]
@mozrt2 no worries at all :) just didn't wanna rug the contribution entirely if ya were still interested
